# Direct Dependabot to maintain dependencies for Glambie.
version: 2
updates:
  # Enable package updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:00"
      timezone: "Europe/London"
    reviewers:
      - "earthwave/engineering"
  - package-ecosystem: "pip"
    directory: "/.github"
    schedule:
      interval: "weekly"
      time: "02:00"
      timezone: "Europe/London"
    reviewers:
      - "earthwave/engineering"
