name: auto_merge_dependabot_prs
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-shared-logic:
    permissions:
      pull-requests: write
      contents: write
    uses: earthwave/ew_continuous_integration/.github/workflows/auto_merge_dependabot_prs_shared.yml@main
