# A reuseable generic pipeline for building a container (if necessary) for testing and deploying Earthwave python packages
name: generic_build_container_if_needed

on:
  workflow_call:
    inputs:
      package_name:
        description: 'The name of the package to build.'
        required: true
        type: string     

jobs:
  build_container_if_necessary:
    # Do we actually need to build the container at all?
    # We build (or rebuild) the container if the package requirements change or it does not already exist.
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    defaults:
      run:
        # This needs to not use pipefail everywhere because failing intermediate lines
        # are used to check whether to build the container or not.
        shell: bash -l {0}
    steps:
      - name: Install dependencies not included in image
        # note we need to install git first or actions/checkout@v3 will use GitHub's REST API instead.
        # TODO: swap this out for a better base container.
        run: |
          apt-get update
          apt-get install -y python3.9 git
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - name: Fix issue with actions/checkout
        # For some reason we can't run later git commands using this image unless we complete this step
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GLAMBIE_GCP_CREDENTIALS }}

      - name: Setup the Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Define container name
        id: name_container
        run: |
          echo "image_name=europe-west1-docker.pkg.dev/glambie/dr/${{ inputs.package_name }}_$(echo "$GITHUB_REF_NAME" | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

      - name: Check if container already exists
        id: check_container
        run: |
          gcloud artifacts docker images list europe-west1-docker.pkg.dev/glambie/dr | grep "${{ steps.name_container.outputs.image_name }}"
          echo "exists=$?" >> $GITHUB_OUTPUT

      - name: Check if package requirements changed
        id: check_files
        # note that we have to run git init to re-initialise the repo before we can run git commands.
        # this is true only when using the ubuntu image.
        run: |
          git diff --exit-code HEAD^ HEAD setup.py
          echo "setup=$?" >> $GITHUB_OUTPUT
          git diff --exit-code HEAD^ HEAD requirements.txt
          echo "requirements=$?" >> $GITHUB_OUTPUT
          git diff --exit-code HEAD^ HEAD .github/test_env_dockerfile
          echo "dockerfile=$?" >> $GITHUB_OUTPUT

      - name: Install Docker
        shell: bash -leo pipefail {0}
        if: |
          steps.check_files.outputs.setup != 0 ||
          steps.check_files.outputs.requirements != 0 ||   
          steps.check_files.outputs.dockerfile != 0 ||
          steps.check_container.outputs.exists != 0
        run: |
          apt-get install -y ca-certificates sudo curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin  

      - name: Authenticate with gcloud
        shell: bash -leo pipefail {0}      
        if: |
          steps.check_files.outputs.setup != 0 ||
          steps.check_files.outputs.requirements != 0 ||
          steps.check_files.outputs.dockerfile != 0 ||
          steps.check_container.outputs.exists != 0      
        run: |
          cat <<EOT > GLAMBIE_GCP_CREDENTIALS.json
          ${{ secrets.GLAMBIE_GCP_CREDENTIALS }}
          EOT
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push this package's test image
        shell: bash -leo pipefail {0}      
        if: |
          steps.check_files.outputs.setup != 0 ||
          steps.check_files.outputs.requirements != 0 ||
          steps.check_files.outputs.dockerfile != 0 ||
          steps.check_container.outputs.exists != 0
        # note that we attempt to pull any existing container first - this allows us to re-use any cached steps from it.
        # we use a multi-stage build so that ew_continuous_integration can be shared across earthwave packages.
        # we pull the operational standard because it contains all of the build layers of the basic standard,
        # even if we're not necessarily building that standard now.
        run: |
          docker pull ${{ steps.name_container.outputs.image_name }} || true
          docker build \
            --cache-from ${{ steps.name_container.outputs.image_name }} \
            --build-arg GLAMBIE_PASSWORD=${{ secrets.GLAMBIE_PASSWORD }} \
            --tag ${{ steps.name_container.outputs.image_name }} -f .github/test_env_dockerfile .
          docker push ${{ steps.name_container.outputs.image_name }}
